<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUrablogCategory extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('urablog_category');
    $this->hasColumn('name', 'string', 255, array('type' => 'string', 'notnull' => true, 'unique' => true, 'length' => '255'));

    $this->option('charset', 'utf8');
  }

  public function setUp()
  {
    $this->hasMany('UrablogField', array('local' => 'id',
                                         'foreign' => 'category_id'));

    $timestampable0 = new Doctrine_Template_Timestampable();
    $this->actAs($timestampable0);
  }
}