<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUrablogBlogBox extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('urablog_blog_box');
    $this->hasColumn('user_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
    $this->hasColumn('title', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
    $this->hasColumn('discri', 'string', 4000, array('type' => 'string', 'length' => '4000'));
    $this->hasColumn('is_active', 'boolean', null, array('type' => 'boolean', 'notnull' => true, 'default' => '1'));

    $this->option('charset', 'utf8');
  }

  public function setUp()
  {
    $this->hasOne('UrablogUser', array('local' => 'user_id',
                                       'foreign' => 'id'));

    $this->hasMany('UrablogField', array('local' => 'id',
                                         'foreign' => 'blog_id'));

    $timestampable0 = new Doctrine_Template_Timestampable();
    $this->actAs($timestampable0);
  }
}