<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUrablogField extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('urablog_field');
    $this->hasColumn('category_id', 'integer', null, array('type' => 'integer'));
    $this->hasColumn('user_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
    $this->hasColumn('blog_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
    $this->hasColumn('title', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
    $this->hasColumn('article', 'string', 4000, array('type' => 'string', 'notnull' => true, 'length' => '4000'));
    $this->hasColumn('is_active', 'boolean', null, array('type' => 'boolean', 'notnull' => true, 'default' => '1'));
    $this->hasColumn('expires_at', 'timestamp', null, array('type' => 'timestamp'));

    $this->option('charset', 'utf8');
  }

  public function setUp()
  {
    $this->hasOne('UrablogCategory', array('local' => 'category_id',
                                           'foreign' => 'id'));

    $this->hasOne('UrablogUser', array('local' => 'user_id',
                                       'foreign' => 'id'));

    $this->hasOne('UrablogBlogBox', array('local' => 'blog_id',
                                          'foreign' => 'id'));

    $timestampable0 = new Doctrine_Template_Timestampable();
    $this->actAs($timestampable0);
  }
}