<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/06/10 22:45:41
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'view',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
