<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UrablogField extends BaseUrablogField
{
  public function __toString()
  {
    return sprintf('Urablog %s', $this->getTitle());
  }
}
