<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/06/10 23:54:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=urablog',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
